// force redeploy
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";

export default function Terms() {
  return (
    <div className="min-h-screen bg-white flex flex-col">
      <Navbar />
      <main className="flex-1 pt-24 pb-16 px-4">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-4xl font-bold text-blue-700 mb-2">Terms of Service</h1>
          <p className="text-sm text-gray-500 mb-10">Effective Date: June 1, 2025</p>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-800 mb-3">1. Acceptance of Terms</h2>
            <p className="text-gray-700 leading-relaxed">
              By accessing or using MergerAid (&ldquo;the Platform&rdquo;), you agree to be bound by these Terms of Service
              (&ldquo;Terms&rdquo;). If you do not agree to these Terms, do not use the Platform. These Terms constitute a legally
              binding agreement between you and MergerAid LLC (&ldquo;Company,&rdquo; &ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;).
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-800 mb-3">2. Description of Service</h2>
            <p className="text-gray-700 leading-relaxed">
              MergerAid provides an automated tax due diligence screening and information platform designed to assist professionals in
              identifying potential tax risk areas in connection with mergers and acquisitions. The Platform generates
              screening reports based on user-provided information.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-800 mb-3">3. Not Legal or Tax Advice</h2>
            <p className="text-gray-700 leading-relaxed mb-3">
              THE PLATFORM DOES NOT PROVIDE TAX ADVICE, LEGAL ADVICE, OR PROFESSIONAL SERVICES OF ANY KIND. MERGERAID IS AN INFORMATION PLATFORM ONLY. All output
              generated by the Platform, including risk summaries, exposure estimates, and reports, is for informational
              and due diligence planning purposes only. Output should not be relied upon as a substitute for advice from
              a qualified tax professional, attorney, or certified public accountant. Exposure estimates are directional
              in nature and may not reflect all applicable taxes, penalties, interest, or jurisdiction-specific rules.
            </p>
            <p className="text-gray-700 leading-relaxed">
              The Company is not a registered tax advisor, law firm, or accounting firm. No attorney-client,
              accountant-client, or advisor-client relationship is created by use of the Platform.
            </p>
            <p className="text-gray-700 leading-relaxed mt-3">
              Exposure estimates generated by the Platform are algorithmic approximations based solely on
              user-provided inputs and generalized tax rate assumptions. They are not based on a review of actual
              tax returns, financial statements, or other primary source documents, and should not be treated as a
              substitute for a formal tax due diligence engagement conducted by a licensed tax professional. Actual
              tax exposure may be materially higher or lower than any estimate generated by the Platform.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-800 mb-3">4. User Responsibilities</h2>
            <p className="text-gray-700 leading-relaxed mb-3">You represent and warrant that:</p>
            <ul className="list-none space-y-2 text-gray-700 leading-relaxed">
              <li>(a) all information you input into the Platform is accurate and complete to the best of your knowledge;</li>
              <li>(b) you understand that the Platform is designed as a preliminary screening tool and not a substitute for professional tax advice; if you are not a qualified tax or financial professional, you agree to seek independent professional advice before acting on any Platform output;</li>
              <li>(c) you will not rely solely on Platform output for any transaction, investment, or business decision;</li>
              <li>(d) you will independently verify all findings with qualified advisors before acting on any output;</li>
              <li>(e) you are at least 18 years of age and have the legal authority to enter into these Terms on behalf of yourself or your organization.</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-800 mb-3">5. Subscription and Payment</h2>
            <p className="text-gray-700 leading-relaxed">
              Access to the Platform requires payment of applicable fees. All fees are non-refundable except as required
              by law. Subscriptions automatically renew unless cancelled before the renewal date. We reserve the right to
              modify pricing with 30 days notice. Payment is processed by Stripe and subject to Stripe&apos;s terms of service.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-800 mb-3">6. Limitation of Liability</h2>
            <p className="text-gray-700 leading-relaxed">
              TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE COMPANY SHALL NOT BE LIABLE FOR ANY INDIRECT,
              INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING OUT OF OR RELATED TO YOUR USE OF THE
              PLATFORM, INCLUDING BUT NOT LIMITED TO LOST PROFITS, LOST DATA, TAX ASSESSMENTS, PENALTIES, INTEREST, OR
              TRANSACTION LOSSES, EVEN IF THE COMPANY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. THE
              COMPANY&apos;S TOTAL CUMULATIVE LIABILITY TO YOU FOR ANY CLAIMS ARISING OUT OF OR RELATED TO THESE TERMS OR THE
              PLATFORM SHALL NOT EXCEED THE TOTAL AMOUNT PAID BY YOU TO THE COMPANY IN THE TWELVE (12) MONTHS PRECEDING
              THE CLAIM.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-800 mb-3">7. Indemnification</h2>
            <p className="text-gray-700 leading-relaxed mb-3">
              You agree to indemnify, defend, and hold harmless the Company and its officers, directors, employees, and
              agents from and against any claims, damages, losses, liabilities, costs, and expenses (including reasonable
              attorneys&apos; fees) arising out of or related to:
            </p>
            <ul className="list-none space-y-2 text-gray-700 leading-relaxed">
              <li>(a) your use of the Platform;</li>
              <li>(b) your violation of these Terms;</li>
              <li>(c) your reliance on Platform output; or</li>
              <li>(d) any third-party claims arising from your use of Platform output in connection with any transaction or professional engagement.</li>
            </ul>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-800 mb-3">8. Intellectual Property</h2>
            <p className="text-gray-700 leading-relaxed">
              All content, software, algorithms, and materials comprising the Platform are the exclusive property of
              MergerAid LLC and are protected by applicable intellectual property laws. You may not reproduce, distribute,
              modify, or create derivative works from any portion of the Platform without our express written consent.
              Reports generated by the Platform may be used internally for due diligence purposes only and may not be
              resold or distributed as a standalone work product.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-800 mb-3">9. Confidentiality</h2>
            <p className="text-gray-700 leading-relaxed">
              You agree to maintain the confidentiality of your account credentials. You are responsible for all activity
              occurring under your account. Notify us immediately of any unauthorized use at{" "}
              <a href="mailto:support@mergeraid.com" className="text-blue-600 hover:underline">support@mergeraid.com</a>.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-800 mb-3">10. Disclaimer of Warranties</h2>
            <p className="text-gray-700 leading-relaxed">
              THE PLATFORM IS PROVIDED &ldquo;AS IS&rdquo; AND &ldquo;AS AVAILABLE&rdquo; WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED,
              INCLUDING BUT NOT LIMITED TO WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, OR
              NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE PLATFORM WILL BE UNINTERRUPTED, ERROR-FREE, OR THAT ANY
              EXPOSURE ESTIMATES WILL BE ACCURATE OR COMPLETE.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-800 mb-3">11. Governing Law and Dispute Resolution</h2>
            <p className="text-gray-700 leading-relaxed">
              Any dispute arising out of or related to these Terms shall be resolved by binding arbitration
              administered by the American Arbitration Association under its Commercial Arbitration Rules. You waive any
              right to participate in a class action lawsuit or class-wide arbitration. These Terms shall be governed
              by the laws of the State of Florida without regard to conflict of law principles, provided that if
              MergerAid LLC is subsequently organized under the laws of another state, the governing law shall be
              updated accordingly with notice to users.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-800 mb-3">12. Modifications</h2>
            <p className="text-gray-700 leading-relaxed">
              We reserve the right to modify these Terms at any time. We will notify you of material changes by email or
              by posting a notice on the Platform. Continued use of the Platform after changes constitutes acceptance of
              the revised Terms.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-800 mb-3">13. Termination</h2>
            <p className="text-gray-700 leading-relaxed">
              We reserve the right to suspend or terminate your access to the Platform at any time for violation of these
              Terms or for any other reason at our sole discretion. Upon termination, your right to use the Platform
              ceases immediately.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-800 mb-3">14. Contact</h2>
            <p className="text-gray-700 leading-relaxed">
              MergerAid LLC &mdash;{" "}
              <a href="mailto:support@mergeraid.com" className="text-blue-600 hover:underline">support@mergeraid.com</a>
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-800 mb-3">15. Intended Users</h2>
            <p className="text-gray-700 leading-relaxed">
              The Platform is designed for use by M&amp;A professionals, business owners, and any individual seeking a
              preliminary screening of potential tax risk areas. It is not intended as a substitute for personalized
              professional tax advice. Regardless of professional background, all users are encouraged to consult with
              a qualified tax advisor, attorney, or certified public accountant before making any decisions based on
              Platform output. The Platform does not assess individual tax situations and is not a replacement for a
              formal tax due diligence engagement.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-800 mb-3">16. Deal Data and Confidentiality</h2>
            <p className="text-gray-700 leading-relaxed">
              MergerAid treats all deal-specific information submitted through the Platform as confidential. We do not
              use your deal data for any purpose other than generating your requested screening output and improving the
              Platform&apos;s functionality in anonymized, aggregated form. We do not share, sell, or disclose
              deal-specific information to any third party except as required by law or as necessary to operate the
              Platform. By submitting deal information, you represent that you have the authority to submit such
              information and that doing so does not violate any confidentiality obligations you may have to third
              parties.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-800 mb-3">17. Force Majeure</h2>
            <p className="text-gray-700 leading-relaxed">
              The Company shall not be liable for any failure or delay in performance resulting from causes beyond its
              reasonable control, including but not limited to acts of God, natural disasters, pandemic, war, terrorism,
              government action, internet or infrastructure outages, or third-party service failures.
            </p>
          </section>

          <section className="mb-8">
            <h2 className="text-xl font-semibold text-gray-800 mb-3">18. Entire Agreement</h2>
            <p className="text-gray-700 leading-relaxed">
              These Terms constitute the entire agreement between you and MergerAid LLC with respect to the Platform
              and supersede all prior agreements, representations, and understandings. If any provision of these Terms
              is found to be unenforceable, the remaining provisions will continue in full force and effect.
            </p>
          </section>
        </div>
      </main>
      <Footer />
    </div>
  );
}
